baseURL = "https://www.newtonwatch.org/"
languageCode = "en-us"
title = "NewtonWatch"
preserveTaxonomyNames = true
copyright = "© 2020-{year} Copyright NewtonWatch. All rights reserved."

[permalinks]
  "/" = "/:year/:month/:day/:title/"
  articles = "/:year/:month/:day/:title/"
  news-clips = "/:year/:month/:day/:title/"

[taxonomies]
  tag = "tags"

[params]
  author = "NewtonWatch"
  description = "NewtonWatch is restoring citizen journalism to the city of Newton."
  twitter = "@newtonwatch"

[markup.goldmark.renderer]
    unsafe= true